

export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES'
export const CREATE_CAMPUS = 'CREATE_CAMPUS'
export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS'
export const SELECT_CAMPUS = 'SELECT_CAMPUS'
export const SELECT_STUDENT = 'SELECT_STUDENT'
export const UPDATE_CAMPUS = 'UPDATE_CAMPUS'
export const CREATE_STUDENT = 'CREATE_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const CHANGE_VIEW = 'CHANGE_VIEW'
export const DELETE_CAMPUS = 'DELETE_STUDENT'
export const CHANGE_ADD_OR_EDIT = 'CHANGE_ADD_OR_EDIT'